/**
 * SES-RDP: tool definitions (name, description, JSON schema) vendored from
 * Desktop Commander's server.ts ListTools handler. Generated by scripts/extract-tools.mjs.
 * UI-preview _meta entries removed; descriptions otherwise unchanged.
 */
import { zodToJsonSchema } from 'zod-to-json-schema';
import { getSystemInfo, getOSSpecificGuidance, getPathGuidance } from './utils/system-info.js';
import {
  StartProcessArgsSchema, ReadProcessOutputArgsSchema, InteractWithProcessArgsSchema,
  ForceTerminateArgsSchema, ListSessionsArgsSchema, KillProcessArgsSchema,
  ReadFileArgsSchema, ReadMultipleFilesArgsSchema, WriteFileArgsSchema,
  CreateDirectoryArgsSchema, ListDirectoryArgsSchema, MoveFileArgsSchema,
  GetFileInfoArgsSchema, GetConfigArgsSchema, SetConfigValueArgsSchema,
  ListProcessesArgsSchema, EditBlockArgsSchema, GetUsageStatsArgsSchema,
  GiveFeedbackArgsSchema, StartSearchArgsSchema, GetMoreSearchResultsArgsSchema,
  StopSearchArgsSchema, ListSearchesArgsSchema, GetPromptsArgsSchema,
  GetRecentToolCallsArgsSchema, WritePdfArgsSchema,
} from './tools/schemas.js';

const SYSTEM_INFO = getSystemInfo();
const OS_GUIDANCE = getOSSpecificGuidance(SYSTEM_INFO);
const PATH_GUIDANCE = `IMPORTANT: ${getPathGuidance(SYSTEM_INFO)} Relative paths may fail as they depend on the current working directory. Tilde paths (~/...) might not work in all contexts. Unless the user explicitly asks for relative paths, use absolute paths.`;
const CMD_PREFIX_DESCRIPTION = `This command can be referenced as "RDP: ..." or "use SES-RDP to ..." in your instructions.`;

export interface ToolDefinition {
  name: string;
  description: string;
  inputSchema: unknown;
  annotations?: Record<string, unknown>;
}

/** Upstream-only onboarding/UI tools; never exposed by SES-RDP. */
export const EXCLUDED_TOOLS = new Set(['give_feedback_to_desktop_commander', 'get_prompts', 'track_ui_event']);

export function buildToolDefinitions(): ToolDefinition[] {
  const allTools: ToolDefinition[] = [
